[general]
import = [
    "~/.config/alacritty/themes/wombat.toml"
]

[window] 
opacity = 0.9

[window.padding]
x = 20
y = 20



[font]
size = 16.0
[font.normal]
family = "FantasqueSansM Nerd Font Propo"
